const express = require('express');
const router = express.Router();

let images=[
  {name: '1', tags: 'venek'},
  {name: '2', tags: 'venek'},
  {name: '3', tags: 'vnitrek veranda'},
  {name: '4', tags: 'vnitrek veranda'},
  {name: '5', tags: 'vnitrek obyvak pokoj'},
  {name: '6', tags: 'vnitrek obyvak pokoj'},
  {name: '7', tags: 'venek'},
  {name: '8', tags: 'venek zahrada'},
  {name: '9', tags: 'vnitrek veranda'},
  {name: '10', tags: 'vnitrek loznice pokoj'},
  {name: '11', tags: 'venek'},
  {name: '12', tags: 'venek'},
  {name: '13', tags: 'venek'},
  {name: '14', tags: 'venek'},
  {name: '15', tags: 'vnitrek'},
  {name: '16', tags: 'vnitrek veranda'},
  {name: '17', tags: 'venek'},
  {name: '18', tags: 'venek balkon'},
  {name: '19', tags: 'vnitrek loznice pokoj'},
  {name: '20', tags: 'vnitrek veranda'},
  {name: '21', tags: 'venek'},
  {name: '22', tags: 'venek'},
  {name: '23', tags: 'vnitrek koupelna'},
  {name: '24', tags: 'vnitrek'},
  {name: '25', tags: 'venek'},
  {name: '26', tags: 'venek veranda'},
  {name: '27', tags: 'venek veranda'},
  {name: '28', tags: 'venek'},
  {name: '29', tags: 'venek pristresek'},
  {name: '30', tags: 'venek zahrada'},
  {name: '31', tags: 'venek garaz'},
  {name: '32', tags: 'venek'},
  {name: '33', tags: 'vnitrek pokoj'},
  {name: '34', tags: 'venek pristresek'},
  {name: '35', tags: 'vnitrek koupelna'},
  {name: '36', tags: 'venek'},
  {name: '37', tags: 'venek zahrada'},
  {name: '38', tags: 'venek zahrada pristresek'},
  {name: '39', tags: 'venek zahrada'},
  {name: '40', tags: 'venek zahrada'},
  {name: '41', tags: 'vnitrek obyvak pokoj'},
  {name: '42', tags: 'vnitrek kuchyn'},
  {name: '43', tags: 'vnitrek garaz'},
  {name: '44', tags: 'venek'},
  {name: '45', tags: 'venek veranda'},
  {name: '46', tags: 'vnitrek koupelna'},
  {name: '47', tags: 'vnitrek pokoj'},
  {name: '48', tags: 'vnitrek obyvak pokoj'},
  {name: '49', tags: 'vnitrek koupelna'},
  {name: '50', tags: 'venek zahrada'},
  {name: '51', tags: 'vnitrek kuchyn'},
  {name: '52', tags: 'vnitrek podkrovi pokoj'},
  {name: '53', tags: 'vnitrek obyvak pokoj'},
  {name: '54', tags: 'venek zahrada'},
  {name: '55', tags: 'venek zahrada'},
  {name: '56', tags: 'vnitrek kuchyn'},
  {name: '57', tags: 'vnitrek garaz'},
]

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { page: 'About us', menuId: 'about' });
});

module.exports = router;
